// GENERATED BY build.gradle.kts -- DO NOT MODIFY
package com.kartikprakash2.multiplatform.tools

import com.kartikprakash2.multiplatform.tools.models.BackgroundJobType
import kotlin.String

public enum class BackgroundJobIdentifiers : BackgroundJobType {
    ID1 {
        override val identifier: String = "ID1"
    },
}
